FROM python:3.12.3

WORKDIR /Consumer

# COPY src/ consumer.py requirements-consumer.txt /Consumer/ # Fix src/ directory
COPY . /Consumer/

RUN pip install -r requirements-consumer.txt

# CMD ["tail", "-f", "/dev/null"]

CMD ["python", "consumer.py"]
