FROM python:3.12.3

WORKDIR /Consumer

COPY src consumer.py /Consumer/

# RUN pip install -r requirements-consumer.txt

CMD ["tail", "-f", "/dev/null"]

# CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--workers", "4", "--bind", "0.0.0.0:8000", "main:app"]
# gunicorn -k uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:8000 main:app
